(function($) {
    $(document).ready(function() {
	
	$('#record_plot').scianimator({
	    'images': ['images/record_plot1.png', 'images/record_plot2.png', 'images/record_plot3.png', 'images/record_plot4.png', 'images/record_plot5.png', 'images/record_plot6.png', 'images/record_plot7.png', 'images/record_plot8.png', 'images/record_plot9.png', 'images/record_plot10.png', 'images/record_plot11.png', 'images/record_plot12.png', 'images/record_plot13.png', 'images/record_plot14.png', 'images/record_plot15.png', 'images/record_plot16.png', 'images/record_plot17.png', 'images/record_plot18.png', 'images/record_plot19.png', 'images/record_plot20.png', 'images/record_plot21.png', 'images/record_plot22.png', 'images/record_plot23.png', 'images/record_plot24.png', 'images/record_plot25.png', 'images/record_plot26.png', 'images/record_plot27.png', 'images/record_plot28.png', 'images/record_plot29.png', 'images/record_plot30.png', 'images/record_plot31.png', 'images/record_plot32.png', 'images/record_plot33.png', 'images/record_plot34.png', 'images/record_plot35.png', 'images/record_plot36.png', 'images/record_plot37.png', 'images/record_plot38.png', 'images/record_plot39.png', 'images/record_plot40.png', 'images/record_plot41.png', 'images/record_plot42.png', 'images/record_plot43.png', 'images/record_plot44.png', 'images/record_plot45.png', 'images/record_plot46.png', 'images/record_plot47.png', 'images/record_plot48.png', 'images/record_plot49.png', 'images/record_plot50.png', 'images/record_plot51.png', 'images/record_plot52.png', 'images/record_plot53.png', 'images/record_plot54.png', 'images/record_plot55.png', 'images/record_plot56.png', 'images/record_plot57.png', 'images/record_plot58.png', 'images/record_plot59.png', 'images/record_plot60.png', 'images/record_plot61.png', 'images/record_plot62.png', 'images/record_plot63.png', 'images/record_plot64.png', 'images/record_plot65.png', 'images/record_plot66.png', 'images/record_plot67.png', 'images/record_plot68.png', 'images/record_plot69.png', 'images/record_plot70.png', 'images/record_plot71.png', 'images/record_plot72.png', 'images/record_plot73.png', 'images/record_plot74.png', 'images/record_plot75.png', 'images/record_plot76.png', 'images/record_plot77.png', 'images/record_plot78.png', 'images/record_plot79.png', 'images/record_plot80.png', 'images/record_plot81.png', 'images/record_plot82.png', 'images/record_plot83.png', 'images/record_plot84.png', 'images/record_plot85.png', 'images/record_plot86.png', 'images/record_plot87.png', 'images/record_plot88.png', 'images/record_plot89.png', 'images/record_plot90.png', 'images/record_plot91.png', 'images/record_plot92.png', 'images/record_plot93.png', 'images/record_plot94.png', 'images/record_plot95.png', 'images/record_plot96.png', 'images/record_plot97.png', 'images/record_plot98.png', 'images/record_plot99.png', 'images/record_plot100.png'],
	    'width': 480,
	    'delay': 10,
	    'loopMode': 'loop',
 'controls': ['first', 'previous', 'play', 'next', 'last', 'loop', 'speed']
	});
	$('#record_plot').scianimator('play');
    });
})(jQuery);
